.TH DESIRE-CLI "1" "June 2016" "desire-cli 0.12"
.SH NAME
desire-cli \- a remote procedure call client for Desire Core. 
.SH SYNOPSIS
desire-cli [options] <command> [params] \- Send command to Desire Core. 
.TP
desire-cli [options] help \- Asks Desire Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the desire-cli program. desire-cli is an RPC client used to send commands to Desire Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBdesired\fP, \fBdesire.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
